<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/10/29
 * Time: 21:02
 */

namespace backend\controllers;


use backend\models\AdminInfo;

class AuthController extends BaseController
{
    protected $userInfo;

    public function beforeAction($action)
    {
        //验证签名
        $header = \Yii::$app->request->headers;
        $token = $header['token'];

        $getPayloadt=\backend\components\Jwt::verifyToken($token);

        if(!$getPayloadt){
            echo json_encode(['code'=>3001,'msg'=>'请登陆','data'=>'']);
            return false;
        }
        if(isset($getPayloadt['data'])){
            $id = $getPayloadt['data']['uid'];
            $res = AdminInfo::findOne($id);
            if($res){
                $this->userInfo = $getPayloadt['data'];

                //记录操作日志
                $controller = \Yii::$app->controller->id;//控制器名称
                $action = $this->action->id;//方法名称
                $ip = \Yii::$app->request->getUserIP();//用户IP
                $user_id = $id;
                $info = 'IP:'.$ip.'----'.'操作URL：'.$controller.'/'.$action;
                $param = \Yii::$app->request->post();
                $param = json_encode($param);
                $time = date('Y-m-d H:i:s');



                return true;
            }else{
                echo json_encode(['code'=>3001,'msg'=>'账号被禁用','data'=>'']);
                return false;
            }
        }else{
            echo json_encode(['code'=>3001,'msg'=>'登陆过期，请重新登陆','data'=>'']);
            return false;
        }
    }



    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub



    }

    //获取用户信息
    public function actionGetUser(){
        return $this->success($this->userInfo);
    }

    public function actionLogout(){
        return $this->success('退出成功');
    }

}
